services:
  app1:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    container_name: 1-nuxt-commerce
    hostname: app1
    # expose:
    #   - 3000
    stdin_open: true
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules:delegated
    restart: on-failure
    networks:
      - comx-net
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - kafka

  app2:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3001:3000
    container_name: 2-nuxt-commerce
    hostname: app2
    # expose:
    #   - 3001
    stdin_open: true
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules:delegated
    restart: on-failure
    networks:
      - comx-net
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - kafka

  app3:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3002:3000
    container_name: 3-nuxt-commerce
    hostname: app3
    # expose:
    #   - 3002
    stdin_open: true
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules:delegated
    restart: on-failure
    networks:
      - comx-net
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - kafka

  rabbitmq:
    image: rabbitmq:3.13.3-management
    restart: unless-stopped
    container_name: nuxt-commerce-rabbitmq
    shm_size: 100mb
    env_file:
      - .env
    expose:
      - 5672
    ports:
      - 15672:15672
    volumes:
      - nuxt-commerce-rabbitmq:/var/lib/rabbitmq
    networks:
      - comx-net

  kafka:
    image: apache/kafka:3.7.0
    restart: unless-stopped
    container_name: nuxt-commerce-kafka
    shm_size: 100mb
    env_file:
      - .env
    expose:
      - 9092
    # ports:
    #   - 29092:29092

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: nuxt-commerce-postgres
    shm_size: 256mb
    env_file:
      - ./.env
    networks:
      - comx-net
    expose:
      - 5432
    volumes:
      - nuxt-commerce-postgres:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    container_name: nuxt-commerce-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    shm_size: 256mb
    env_file:
      - ./.env
    ports:
      - 6379:6379
    volumes:
      - ./redis:/usr/local/etc/redis
      - nuxt-commerce-redis:/data
    networks:
      - comx-net
    # nginx:
    #   image: nginx:1.27-alpine-perl
    #   restart: unless-stopped
    #   ports:
    #     - "80:80"
    #   depends_on:
    #     - app
    #   networks:
    #     - comx-net

  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  node_modules:
  nuxt-commerce-postgres:
  nuxt-commerce-redis:
  nuxt-commerce-rabbitmq:


networks:
  comx-net:
    name: comx-net
    driver: bridge
    external: true
