services:
  app1:
    build:
      context: ./
    # ports:
    #   - "3000:3000"
    container_name: nuxt-commerce-1
    hostname: app1
    expose:
      - 3000
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      # - .:/usr/app
      - ./node_modules:/app/node_modules
    restart: on-failure
    depends_on:
      - postgres
      - redis
      - rabbitmq
      # - kafka

  app2:
    build:
      context: ./
    # ports:
    #   - "3001:3000"
    container_name: nuxt-commerce-2
    hostname: app2
    expose:
      - 3001
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      # - .:/usr/app
      - ./node_modules:/app/node_modules
    restart: on-failure
    depends_on:
      - postgres
      - redis
      - rabbitmq
      # - kafka

  app3:
    build:
      context: ./
    # ports:
    #   - "3002:3000"
    container_name: nuxt-commerce-3
    hostname: app3
    expose:
      - 3002
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      # - .:/usr/app
      - ./node_modules:/app/node_modules
    restart: on-failure
    depends_on:
      - postgres
      - redis
      - rabbitmq
      # - kafka

  rabbitmq:
    image: rabbitmq:4.0.3-alpine
    restart: unless-stopped
    container_name: nuxt-commerce-rabbitmq
    shm_size: 100mb
    env_file:
      - ./.env
    expose:
      - 5672
      - 15672
    deploy:
      resources:
        limits:
          memory: 256M
    # TODO Check this port
    # ports:
    #   - "15672:15672"
    volumes:
      - ./nuxt-commerce-rabbitmq:/var/lib/rabbitmq

  # kafka:
  #   image: apache/kafka:alpine
  #   restart: unless-stopped
  #   container_name: nuxt-commerce-kafka
  #   shm_size: 100mb
  #   env_file:
  #     - ./.env
  #   expose:
  #     - 9092
  #   # ports:
  #   #   - '29092:29092'

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: nuxt-commerce-postgres
    shm_size: 256mb
    env_file:
      - ./.env
    expose:
      - 5432
    volumes:
      - ./nuxt-commerce-postgres:/var/lib/postgresql/data
    # ports:
    #   - '5432:5432'

  redis:
    image: redis:7.4.1-alpine
    restart: on-failure
    hostname: redis
    container_name: nuxt-commerce-redis
    # command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    # command: sudo service redis-server start
    # command: redis-server --requirepass ${REDIS_PASSWORD} --save 300 1 --loglevel warning
    shm_size: 256mb
    env_file:
      - ./.env
    # ports:
    #   - "6379:6379"
    expose:
      - 6379
    volumes:
      # - ./redis.conf:/etc/redis/redis.conf
      - ./redis:/usr/local/etc/redis
      - ./nuxt-commerce-redis:/data

  nginx:
    # image: nginx:1.27.2-alpine
    build:
      context: ./nginx
    container_name: nuxt-commerce-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3

volumes:
  node_modules:
  nuxt-commerce-postgres:
  nuxt-commerce-redis:
  nuxt-commerce-rabbitmq:
